### ISSUE TITLE
additional submenu levels not rendered

### ISSUE THREAD

**Issue by amygroshek** [lazydaisy/Moodle-Studio#2]
Hi Mary,

I've been playing with this theme. I noticed that submenus do not work. The little carrot renders to indicate a submenu should be there, but when the parent of the submenu `<li>` is printed to the page it doesn't have the correct dropdown-submenu class on it. 

I am able to hack the renderer and make the first drop-down work with this (starting around line 344 of your renderers.php): 

``` php
if ($menunode->has_children()) {
            if ($submenucount == 0) {
                $content = html_writer::start_tag('li', array('class'=>'dropdown'));
            } else {
                $content = html_writer::start_tag('li', array('class'=>'dropdown-submenu'));
            }
```

But even that doesn't fix things for the next `<li>` at the base level. This is because I'm basing the logic off of $submenucount.  I can't figure out how to get from the $menuitem object what I need, which seems like it would be the sort value. Seems that if sort > 1 and the `li` has children it needs the dropdown-submenu class. 

I don't really know enough PHP to get farther with a fix, and I've no idea whether this is something you're interested in. But from my tests, it just looks like the classname assignment in the menu is a bit off, and with some tweaking would work. 

Regards,
Amy

**Comment by lazydaisy** [comment]
Hi Amy,

Do you mean the Tiny (Bootstrap) theme? The menu is a pain, and I am not sure myself how to get it to work correctly.
The fact it that the actual Bootstrap menu was never designed for sub-menus, and my intention was not to use them and add this fact to the README file in the theme.

I don't know enough about PHP either, but will take a look at what you have done and see if I can work out a way forward. 

Thanks
Mary

**Comment by lazydaisy** [comment]
Hi Amy,
I've just given up on this for the moment. It needs some more IF statements to partition off the different types of menus which are at play. I noticed that with the code you proposed, the behaviour of the first-level and the second-level sub-menus are the same. The second-level work great, bobbing out to the side, but this also happens to the first-level one too.
Here is a copy of the menu I am testing it with, just in case you are confused with my reference to 1st and 2nd level. :)

Moodle community|http://moodle.org||en
-Moodle free support|http://moodle.org/support||en
-Moodle development|http://moodle.org/development||en
-Moodle News|http://moodle.org/news||en
--Moodle News|http://moodle.org/news||en
--Moodle News|http://moodle.org/news||en
Moodle company|||en
-Moodle commercial hosting|http://moodle.com/hosting||en
-Moodle commercial support|http://moodle.com/support||en
-Moodle commercial hosting|http://moodle.com/hosting||en
-Moodle commercial support|http://moodle.com/support||en
-Moodle commercial hosting|http://moodle.com/hosting||en
-Moodle commercial support|http://moodle.com/support||en

**Comment by amygroshek** [comment]
Hi Mary,

I was thinking that if we could extract the "sort" value from the $menunode object, and that would tell us what we need to apply the correct class. 

It looks like it is available from outputcomponents.php: 

``` php
    /**
     * Gets the sort order for this child
     * @return int
     */
    public function get_sort_order() {
        return $this->sort;
    }
```

But it looks like that is just sort order, not a level-type designation... 

It would probably have to be some sort of combination of has children and has parents conditional statements. If I get a little more time I'll give it another try.

Regards,
A

**Comment by amygroshek** [comment]
OK, this is what I've got currently. It works except that there are two submenu-indicator carrots being rendered on items that have a submenu.

Starting on line 344:

``` php
if ($menunode->has_children()) {
            if ( !count($menunode->get_parent()) ) {
                $content = html_writer::start_tag('li', array('class'=>'dropdown'));
            } else {
                $content = html_writer::start_tag('li', array('class'=>'dropdown-submenu'));
            }
```

**Comment by lazydaisy** [comment]
Excellent!  I have just tested it now and yes that does the trick! 

Thanks :)

**Comment by amygroshek** [comment]
Sweet! Now if we can just make it accessible it's a replacement for the YUI custommenu.

**Comment by lazydaisy** [comment]
I have been thinking about how to do just that too. 
We could do with adding some ARIA code: http://www.w3.org/TR/wai-aria/
There is a suggestion here we could try which doesn't look too difficult: http://terrillthompson.com/blog/202
We would need a counter for tabindex="0" which is similar to the submenu counter that is in place already, so perhaps we can learn how to do this, which again should not be too difficult, but putting it all together to make it work may be a challenge. :)

**Comment by amygroshek** [comment]
I would love to work with you on this. 

Do you have a good workflow for cloning into your theme directory? It seems like I can't clone this whole repo into a theme dir and have it work... Am I wrong?

**Comment by amygroshek** [comment]
`get_sort_order()` may be useful for building tabindex. I'll have to look at the links you provide.

**Comment by lazydaisy** [comment]
This actual theme is just a copy, of my working copy, which is on my localhost server running a Moodle clone, and not connected to this repo at all.

I realise now that this is not the best way to have done it, but then I was only using Moodle-Studio as a repo for my themes, hence the theme branch names.

To be honest, I don't know how you would clone it into the theme's directory in Moodle.

What I do is just physically copy and paste the Tiny folder into Moodle. After I have made changes to it. I copy and paste it back and PUSH it back here. Which is really defeating the object of GIT. :)

**Comment by lazydaisy** [comment]
Hi Amy,
Have you made a FORK of the Moodle-Studio repository?

**Comment by lazydaisy** [comment]
Amy,
Thanks to your earlier fix I managed to get rid of the caret in the submenu now only the > indicator shows. 
The fix is at or about line 360. :)  

```
        $content .= html_writer::start_tag('a', array('href'=>$url,'class'=>'dropdown-toggle','data-toggle'=>'dropdown'));
        $content .= html_writer::start_tag('i', array('class'=>"icon-leaf icon-white"));
        $content .= html_writer::end_tag('i').'&nbsp;';
        $content .= $menunode->get_title().'&nbsp;';

    // this adds the caret to the parent only
    if ( !count($menunode->get_parent()) ) {
        $content .= html_writer::start_tag('b', array('class'=>'caret'));
        $content .= html_writer::end_tag('b');
    }
        $content .= html_writer::end_tag('a');
        $content .= html_writer::start_tag('ul', array('class'=>'dropdown-menu'));
        foreach ($menunode->get_children() as $menunode) {
        $content .= $this->render_custom_menu_item($menunode);
```

I'll update this all tomorrow when I'll create a new repo and add this as the master branch, which should make it easier for you to clone and help with collaboration. :)

Many thanks for your help with this so far.

By the way, have you seen this from Twitter Bootstrap...
http://twitter.github.com/bootstrap/components.html
it explains more about the menu/submenu and introduces ARIA code too.
